name: flutter-gallery
adopt-info: flutter-gallery
summary: Flutter Gallery
description: |
  A demo app for Flutter's material design and cupertino widgets, as well as many other features of the Flutter SDK.
grade: stable
confinement: strict
base: core22

architectures:
  - build-on: amd64
  - build-on: arm64

slots:
  # for GtkApplication registration
  flutter-gallery:
    interface: dbus
    bus: session
    name: io.flutter.demo.gallery

apps:
  daemon:
    daemon: simple
    restart-condition: always
    environment:
      LC_ALL: en_UK.UTF-8
      FLUTTER_GALLERY_FULLSCREEN: 1
      LIBGL_ALWAYS_SOFTWARE: 1
    command-chain:
      - bin/run-daemon
      - bin/wayland-launch
    command: bin/flutter_gallery
    extensions: [gnome]
    plugs:
      - opengl
      - wayland
      - network

  flutter-gallery:
    command: bin/flutter_gallery
    extensions: [gnome]
    plugs:
      - opengl
      - network

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-branch: stable
    plugin: nil
    override-build: |
      set -eux
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -sf $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      export PATH="$CRAFT_PART_INSTALL/usr/bin:$PATH"
      flutter doctor
      flutter channel stable
      flutter upgrade
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
    override-prime: ''

  flutter-gallery:
    after: [ flutter-git ]
    source: https://github.com/flutter/gallery.git
    source-tag: v2.9.2
    plugin: nil
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10)
    override-build: |
      set -eux
      flutter pub get
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/

  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $CRAFT_PART_BUILD/build-with-plugs.sh opengl wayland network
    stage-packages:
      - inotify-tools

  assets:
    plugin: nil
    stage-packages:
    - dmz-cursor-theme
    - fonts-dejavu
    - fonts-freefont-ttf
    - fonts-ubuntu

layout:
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
