name: flutter-gallery
adopt-info: flutter-gallery
summary: Flutter Gallery
description: |
  A demo app for Flutter's material design and cupertino widgets, as well as many other features of the Flutter SDK.
grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64

slots:
  # for GtkApplication registration
  flutter-gallery:
    interface: dbus
    bus: session
    name: io.flutter.demo.gallery

apps:
  daemon:
    daemon: simple
    restart-condition: always
    environment:
      LC_ALL: en_UK.UTF-8
      FLUTTER_GALLERY_FULLSCREEN: 1
    command-chain:
      - snap/command-chain/desktop-launch
      - bin/run-daemon
      - bin/wayland-launch
    command: bin/flutter_gallery
    plugs:
      - opengl
      - wayland
      - network

  flutter-gallery:
    command: bin/flutter_gallery
    extensions: [flutter-master]
    plugs:
      - opengl
      - network

parts:
  flutter-gallery:
    source: https://github.com/flutter/gallery.git
    source-commit: 358fe2dd7daeacc4f5397b2fc91637f79b3d95f8
    plugin: flutter
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git describe --tags --abbrev=10)

  mir-kiosk-snap-launch:
    plugin: dump
    source: https://github.com/MirServer/mir-kiosk-snap-launch.git
    override-build:  $SNAPCRAFT_PART_BUILD/build-with-plugs.sh opengl wayland network
    stage-packages:
      - inotify-tools

  assets:
    plugin: nil
    stage-packages:
    - dmz-cursor-theme
    - fonts-dejavu
    - fonts-freefont-ttf
    - fonts-ubuntu

layout:
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
